### ISSUE TITLE
通过API删除用户失败

### ISSUE THREAD

**Issue by ronysun** [v2ray/discussion#429]
现在使用的v2ray-core是4.21.3版本，能够通过API正确获取到用户流量，但移除用户时提示如下错误：
  File "/usr/local/lib/python3.6/dist-packages/v2ray-0.1-py3.6.egg/v2ray/client.py", line 144, in remove_user
    email=email
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "v2ray.com/core/app/proxyman/command: proxy is not a UserManager"
        debug_error_string = "{"created":"@1573632652.630085579","description":"Error received from peer ipv4:127.0.0.1:18399","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"v2ray.com/core/app/proxyman/command: **proxy is not a UserManager**","grpc_status":2}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "v2ray/user_manage.py", line 48, in <module>
    c.remove_user("api", "47332@126.com")
  File "/usr/local/lib/python3.6/dist-packages/v2ray-0.1-py3.6.egg/v2ray/client.py", line 154, in remove_user
    raise V2RayError(details)
errors.V2RayError: v2ray.com/core/app/proxyman/command: **proxy is not a UserManage**r

**Comment by ronysun** [comment]
问题已解决，在remove_user方法中传入的inbound_tag需要在v2ray的配置文件中进行设置，且此处的inboud_tag不是api
