### ISSUE TITLE
Python调用api问题

### ISSUE THREAD

**Issue by liuerhang** [v2ray/discussion#597]
以下是用grpc编译proto文件后目录
```
├── mytest.py
└── v2ray
    └── com
        └── core
            ├── app
            │   ├── commander
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── dispatcher
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── dns
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── log
            │   │   ├── command
            │   │   │   ├── config_pb2.py
            │   │   │   └── config_pb2_grpc.py
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── policy
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── proxyman
            │   │   │   ├── command_pb2.py
            │   │   │   └── command_pb2_grpc.py
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── reverse
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── router
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   └── stats
            │       ├── command
            │       │   ├── command_pb2.py
            │       │   └── command_pb2_grpc.py
            │       ├── config_pb2.py
            │       └── config_pb2_grpc.py
            ├── common
            │   ├── log
            │   │   ├── log_pb2.py
            │   │   └── log_pb2_grpc.py
            │   ├── net
            │   │   ├── address_pb2.py
            │   │   ├── address_pb2_grpc.py
            │   │   ├── destination_pb2.py
            │   │   ├── destination_pb2_grpc.py
            │   │   ├── network_pb2.py
            │   │   ├── network_pb2_grpc.py
            │   │   ├── port_pb2.py
            │   │   └── port_pb2_grpc.py
            │   ├── protocol
            │   │   ├── headers_pb2.py
            │   │   ├── headers_pb2_grpc.py
            │   │   ├── server_spec_pb2.py
            │   │   ├── server_spec_pb2_grpc.py
            │   │   ├── user_pb2.py
            │   │   └── user_pb2_grpc.py
            │   └── serial
            │       ├── typed_message_pb2.py
            │       └── typed_message_pb2_grpc.py
            ├── config_pb2.py
            ├── config_pb2_grpc.py
            ├── proxy
            │   ├── blackhole
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── dns
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── dokodemo
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── freedom
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── http
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── mtproto
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── shadowsocks
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   ├── socks
            │   │   ├── config_pb2.py
            │   │   └── config_pb2_grpc.py
            │   └── vmess
            │       ├── account_pb2.py
            │       ├── account_pb2_grpc.py
            │       ├── inbound
            │       │   ├── config_pb2.py
            │       │   └── config_pb2_grpc.py
            │       └── outbound
            │           ├── config_pb2.py
            │           └── config_pb2_grpc.py
            └── transport
                ├── config_pb2.py
                ├── config_pb2_grpc.py
                └── internet
                    ├── config_pb2.py
                    ├── config_pb2_grpc.py
                    ├── domainsocket
                    │   ├── config_pb2.py
                    │   └── config_pb2_grpc.py
                    ├── headers
                    │   ├── http
                    │   │   ├── config_pb2.py
                    │   │   └── config_pb2_grpc.py
                    │   ├── noop
                    │   │   ├── config_pb2.py
                    │   │   └── config_pb2_grpc.py
                    │   ├── srtp
                    │   │   ├── config_pb2.py
                    │   │   └── config_pb2_grpc.py
                    │   ├── tls
                    │   │   ├── config_pb2.py
                    │   │   └── config_pb2_grpc.py
                    │   ├── utp
                    │   │   ├── config_pb2.py
                    │   │   └── config_pb2_grpc.py
                    │   ├── wechat
                    │   │   ├── config_pb2.py
                    │   │   └── config_pb2_grpc.py
                    │   └── wireguard
                    │       ├── config_pb2.py
                    │       └── config_pb2_grpc.py
                    ├── http
                    │   ├── config_pb2.py
                    │   └── config_pb2_grpc.py
                    ├── kcp
                    │   ├── config_pb2.py
                    │   └── config_pb2_grpc.py
                    ├── quic
                    │   ├── config_pb2.py
                    │   └── config_pb2_grpc.py
                    ├── tcp
                    │   ├── config_pb2.py
                    │   └── config_pb2_grpc.py
                    ├── tls
                    │   ├── config_pb2.py
                    │   └── config_pb2_grpc.py
                    ├── udp
                    │   ├── config_pb2.py
                    │   └── config_pb2_grpc.py
                    └── websocket
                        ├── config_pb2.py
                        └── config_pb2_grpc.py
```
以下是mytest.py文件代码
```
import grpc

from v2ray.com.core.app.stats.command import command_pb2
from v2ray.com.core.app.stats.command import command_pb2_grpc


def Getstats():
    channel = grpc.insecure_channel('localhost:10085')
    stub = command_pb2_grpc.StatsServiceStub(channel)
    response = stub.QueryStats(command_pb2.QueryStatsRequest(reset=False))
    print(response.message)


if __name__ == '__main__':
    Getstats()
```
以下是v2ray配置文件(实例在wsl中运行，outbound接的是windows版v2ray开的socks5端口,邮箱已隐去)
```
{
    "log": {
    "loglevel": "debug"},
    "stats": {},
    "api": {
        "tag": "api",
        "services": [
            "StatsService",
            "HandlerService"
        ]
    },
    "policy": {
        "levels": {
            "1": {
                "statsUserUplink": true,
                "statsUserDownlink": true
            }
        },
        "system": {
            "statsInboundUplink": true,
            "statsInboundDownlink": true
        }
    },
    "inbounds": [
        {
            "tag": "tcp",
            "port": 3307,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "email": "123@123.com",
                        "id": "e731f153-4f31-49d3-9e8f-ff8f396135ef",
                        "level": 1,
                        "alterId": 64
                    },
                    {
                        "email": "buser",
                        "id": "e731f153-4f31-49d3-9e8f-ff8f396135ee",
                        "level": 1,
                        "alterId": 64
                    }
                ]
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 10085,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "tag": "api"
        }
    ],
    "outbounds": [
        {
            "protocol": "socks",
            "settings": {
                "servers": [{
                    "address": "127.0.0.1",
                    "port": 1080
                    }]}
        }
    ],
    "routing": {
        "settings": {
            "rules": [
                {
                    "inboundTag": [
                        "api"
                    ],
                    "outboundTag": "api",
                    "type": "field"
                }
            ]
        },
        "strategy": "rules"
    }
}
```
v2ray启动后使用v2ctl查询(正常)
```
/usr/bin/v2ray/v2ctl api --server=127.0.0.1:10085 StatsService.QueryStats 'pattern: "" reset: false'
stat: <
  name: "inbound>>>tcp>>>traffic>>>uplink"
>
stat: <
  name: "inbound>>>tcp>>>traffic>>>downlink"
>
stat: <
  name: "inbound>>>api>>>traffic>>>uplink"
  value: 194
>
stat: <
  name: "inbound>>>api>>>traffic>>>downlink"
  value: 54
>
```
但使用mytest.py后出现错误
```
python mytest.py
Traceback (most recent call last):
  File "mytest.py", line 15, in <module>
    Getstats()
  File "mytest.py", line 10, in Getstats
    response = stub.QueryStats(command_pb2.QueryStatsRequest(reset=False))
  File "/home/murasame/prac/pyv2ray/lib/python3.7/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/murasame/prac/pyv2ray/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1583725241.682780200","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Socket closed","grpc_status":14}"
>
```

**Comment by liuerhang** [comment]
已确认是wsl问题，将代码原封不动复制到windows下运行，无任何错误

**Comment by lzkgbld** [comment]
您好，我想请问您是想实现Python调用API然后模拟v2ray的连接吗？请问您能分享一下您的代码，我尝试模拟连接报错内容是：
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Trying to connect an http1.x server"
	debug_error_string = "{"created":"@1595085656.462000000","description":"Error received from peer ipv4:119.39.28.9:20020","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Trying to connect an http1.x server","grpc_status":12}"
>
所以我想借鉴一下您的代码，查询一下错误...感谢

**Comment by ghost** [comment]
> 您好，我想请问您是想实现Python调用API然后模拟v2ray的连接吗？请问您能分享一下您的代码，我尝试模拟连接报错内容是：
> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
> status = StatusCode.UNIMPLEMENTED
> details = "Trying to connect an http1.x server"
> debug_error_string = "{"created":"@1595085656.462000000","description":"Error received from peer ipv4:119.39.28.9:20020","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Trying to connect an http1.x server","grpc_status":12}"
> 
> > 
> 
> 所以我想借鉴一下您的代码，查询一下错误...感谢

能否看下你的，我的还在私有库

**Comment by ghost** [comment]
> 您好，我想请问您是想实现Python调用API然后模拟v2ray的连接吗？请问您能分享一下您的代码，我尝试模拟连接报错内容是：
> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
> status = StatusCode.UNIMPLEMENTED
> details = "Trying to connect an http1.x server"
> debug_error_string = "{"created":"@1595085656.462000000","description":"Error received from peer ipv4:119.39.28.9:20020","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Trying to connect an http1.x server","grpc_status":12}"
> 
> > 
> 
> 所以我想借鉴一下您的代码，查询一下错误...感谢

如果您使用wsl，请将代码拿到vps上去允许试试

**Comment by lzkgbld** [comment]
看到您的回复，十分感谢您愿意花时间解决我这边问题。
我是使用https://github.com/spencer404/v2ray_api
这个项目里面的文件，我也按照他步骤进行处理。但是依旧报错....
我的源码：
[v2ray_api-master.zip](https://github.com/v2ray/discussion/files/4942153/v2ray_api-master.zip)
我将他案例代码写入Demo，由于隐私我并没有填写相关参数，请大佬指点！
感谢您的回复！

**Comment by ghost** [comment]
![20200719_020849](https://user-images.githubusercontent.com/41338932/87859027-d83cd780-c964-11ea-93d3-90d09d567cbd.jpg)
等一下等一下,我看着我自己改的版本来给你改了，图中第一个错您考虑下，第二个继续用字典，我的库里要求是传
list，你这边是加了星号

大概就这些，还有你的包跟我不一样https://github.com/liuerhang/v2ray_python_client
我还有个自己修改的版本，过会儿拿来你看看(明天用电脑，今天先睡觉)

> 看到您的回复，十分感谢您愿意花时间解决我这边问题。
> 我是使用https://github.com/spencer404/v2ray_api
> 这个项目里面的文件，我也按照他步骤进行处理。但是依旧报错....
> 我的源码：
> [v2ray_api-master.zip](https://github.com/v2ray/discussion/files/4942153/v2ray_api-master.zip)
> 我将他案例代码写入Demo，由于隐私我并没有填写相关参数，请大佬指点！
> 感谢您的回复！

**Comment by lzkgbld** [comment]
由于我第一次跨语言写代码，对于转编译成py语言我还是明白的，但是对于那API调用那块，我确实是搞不懂，您是怎么看懂调用V2ray的API的，因为不管怎么看也是GO进行调用，或者说您把GO调用他们API的那些源码也转换成了py进行分析吗？
我下载您的GitHub源码，然后看了一下客户端源码，有点蒙圈，您说调用您的auto_proto_process.py更新源码之后就可以随便使用client了，但是我打开您的client.py，并不知道怎么进行修改，我会尽可能去把这些API调用案例转换成py语言进行分析。
感谢您回复和解答，因为我这个压缩包使用的是其他人源码，所以我有点不明白什么意思，但是我会看看您发给我v2ray_python_client这个源码里面文件信息。

**Comment by lzkgbld** [comment]
感谢您的回复和解答，但是我尝试去分析三个server文件：
v2ray/com/core/app/proxyman/command/command.proto
v2ray/com/core/app/stats/command/command.proto
v2ray/com/core/app/log/command/config.proto
我还是有点难以理解，这个客户端我应该如何配置能够实现连接...感谢您的帮助，如果您觉得厌烦了，也可以直接和我说，不过后面麻烦留一下您的联系方式，不管是Telegram或者邮箱都行，感谢。

我尝试修改client.py文件里面mian函数里面的参数
![image](https://user-images.githubusercontent.com/46844055/87870597-2e992d00-c9dc-11ea-941c-bd1adbdf40cf.png)
是否是在这四处填上v2ray上的服务器参数？
我尝试运行可是他报错：
![image](https://user-images.githubusercontent.com/46844055/87870642-a36c6700-c9dc-11ea-8317-bb46be9573d9.png)
十分感谢您的帮助。

**Comment by lzkgbld** [comment]
网上也没详细调用API的方式或者一些相关资料，只能找到您的，关于https://medium.com/@TachyonDevel/%E8%B0%83%E7%94%A8-v2ray-%E6%8F%90%E4%BE%9B%E7%9A%84-api-%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%94%A8%E6%88%B7%E5%A2%9E%E5%88%A0%E6%93%8D%E4%BD%9C-adf9ff972973
这个网址里面的方法，我实在难以理解如何转换成我Python进行调用的API....十分抱歉，如果您不想回复了，可以直接在问题里面答复一下，然后我希望能取得您一些联系方式，感谢您之前的帮助。
