### ISSUE TITLE
can't read soft link of a config file

### ISSUE THREAD

**Issue by meliber** [v2ray/discussion#623]
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/amd64)
after update to v4.23.1, v2ray fails to launch with an error message 'config file Permission denied'.
/ect/v2ray/config.json is a soft link points to ~/v2ray_config.json
v2ray launched successfully after these operations:

sudo rm /etc/v2ray/config.json
sudo cp ~/v2ray_config.json /etc/v2ray/config.json

Is this a bug?

**Comment by kslr** [comment]
>  Permission denied
try chmod

**Comment by netcaf** [comment]
I have the same issue when clienth.json is a symbolic link, but it's OK if i start the v2ray server in command line.

```
Sep 23 17:26:06 alarmpi v2ray[1308]: main: failed to read config files: [/etc/v2ray/clienth.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:
Sep 23 17:26:06 alarmpi v2ray[1308]: v2ctl> Read config:  /etc/v2ray/clienth.json
Sep 23 17:26:06 alarmpi v2ray[1308]: panic: open /etc/v2ray/clienth.json: permission denied
Sep 23 17:26:06 alarmpi v2ray[1308]: goroutine 1 [running]:
Sep 23 17:26:06 alarmpi v2ray[1308]: v2ray.com/core/common.Must(...)
Sep 23 17:26:06 alarmpi v2ray[1308]:         v2ray.com/core/common/common.go:26
Sep 23 17:26:06 alarmpi v2ray[1308]: v2ray.com/core/infra/control.(*ConfigCommand).Execute(0x136387c, 0x1d120f0, 0x1, 0x2, 0x1d23768, 0x4825c901)
Sep 23 17:26:06 alarmpi v2ray[1308]:         v2ray.com/core/infra/control/config.go:42 +0x544
Sep 23 17:26:06 alarmpi v2ray[1308]: main.main()
Sep 23 17:26:06 alarmpi v2ray[1308]:         v2ray.com/core/infra/control/main/main.go:35 +0x1f0 > exit status 2
Sep 23 17:26:06 alarmpi systemd[1]: v2ray@clienth.service: Main process exited, code=exited, status=23/n/a
Sep 23 17:26:06 alarmpi systemd[1]: v2ray@clienth.service: Failed with result 'exit-code'.
```

V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/arm)
A unified platform for anti-censorship.
